name: SingleDog
main: xiaokai.singledog.SingleDog
api:
- 1.0.0
version: 1.1.2
load: POSTWORLD
website: http://EpicFX.cn
author: Winfxk
description: 结婚插件
depend:
- EconomyAPI
permissions:
   SingleDog.Command.Main:
      description: 结婚主命令
      default: true
   SingleDog.Command.Admin:
      description: 结婚管理员命令
      default: op